style quick settings buttons like zoom buttons
cgeo/cgeo pull request #12131
Opened 2021-11-19 18:31 UTC by ztNFny

Use ImageButton instead of Button to remove outlines on map settings buttons

![image](https://user-images.githubusercontent.com/1258173/142673464-82908efe-7a13-42c7-af55-8fac1cb4a929.png)

## Related issues
fixes #12041

2021-11-19 19:00 UTC, bekuno commented
retest this please

2021-11-19 19:18 UTC, ztNFny commented
retest this please

2021-11-19 19:25 UTC, moving-bits requested changes

2021-11-19 19:25 UTC, moving-bits commented on main/src/cgeo/geocaching/utils/EmojiUtils.java
> +            /* numbers */       0x31, 0x32, 0x33
This is some different change - introducing numbers as emojis?
Should be a separate PR, and (IIRC) should go from 0 to 9 to cover ten stage lab adventures as well.

2021-11-19 19:25 UTC, moving-bits commented on main/src/cgeo/geocaching/maps/CGeoMap.java
> +            //getIndividualRouteUtils().onPrepareOptionsMenu(menu, activity.findViewById(R.id.container_individualroute), individualRoute, StringUtils.isNotBlank(targetGeocode) && null != lastNavTarg
Why did you comment out this line?

2021-11-19 20:00 UTC, ztNFny commented
oops, had the wrong upstream configured, fixed now

2021-11-19 20:15 UTC, moving-bits approved these changes
LGTM, thanks for fixing the issues

2021-11-19 21:07 UTC, bekuno commented
retest this please

2021-11-19 21:23 UTC, bekuno commented
Looks like a bigger problem on CI:
~~~
Installing APK 'cgeo-debug.apk' on 'android-30(AVD) - 11' for main:basic-debug
Unable to install /home/jenkins/slave/workspace/cgeo CI - PR build/main/build/outputs/apk/basic/debug/cgeo-debug.apk
com.android.ddmlib.InstallException: Unknown failure: Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/cgeo-debug.apk: Failed to parse /data/local/tmp/cgeo-debug.apk
~~~
@mucek4 Please restart the executor(s).

2021-11-20 11:31 UTC, moving-bits commented
retest this please

2021-11-21 12:07 UTC, moving-bits commented
retest this please

2021-11-21 18:08 UTC, ztNFny commented
retest this please

2021-11-21 21:45 UTC, moving-bits requested changes

2021-11-21 21:45 UTC, moving-bits commented on main/res/drawable/white_bcg.xml
> +            <corners android:radius="2dp" />/>
somehow the closing tag got duplicated

2021-11-22 14:54 UTC, moving-bits approved these changes
thanks for fixing the duplication

2021-11-22 14:55 UTC, merged