centerCrop wallpaper on home screen (fix #12654)
cgeo/cgeo pull request #12662
Opened 2022-02-02 21:17 UTC by moving-bits

## Description
Instead of using the wallpaper image as background drawable add an `ImageView` to the bottom navigation activity, so that we are able to use `scaleType=centerCrop`, which centers the image and crops everything that got too large. It's probably still not 100% the same for some launchers, but comes pretty close to what the default launcher does with the wallpaper.

|Resulting image is like this:|instead of this:|
|---|---|
|![image](https://user-images.githubusercontent.com/3754370/152238620-94b2e244-d488-4584-951b-a409bbb8603c.png)|![image](https://user-images.githubusercontent.com/3754370/151707413-899a88da-a069-4158-9442-08eda66e5143.png)|

2022-02-02 22:30 UTC, fm-sys requested changes
Please be aware, there is a second layout file involved for landscape... 

But as the background image is only used for MainActivity anyway, we should IMHO not add that view to the general bottom navigation layout but the the MainActivity layout

2022-02-04 09:24 UTC, moving-bits commented
> Please be aware, there is a second layout file involved for landscape...

Ah, good to know, thanks for mentioning it. => I'll adapt the PR.

> But as the background image is only used for MainActivity anyway, we should IMHO not add that view to the general bottom navigation layout but the the MainActivity layout

I had it this way in the first version of this PR, but then the image will centered within the dashboard's dimensions only, not centered relative to the whole display, which would lead to a very visible difference to the wallpaper look, as the dashboard's center is more upward than the display's center.

But having the `ImageView` defined in the base layout should be no problem, as it gets filled in `MainActivity` only. When switching through the other buttom navigation activities, there will be no wallpaper visible.

2022-02-04 20:19 UTC, moving-bits commented
Adapted PR to support landscape layouts as well:

![image](https://user-images.githubusercontent.com/3754370/152597622-4bcf35c1-120a-477c-93f6-1e5b7ceb7a11.png)

2022-02-04 22:06 UTC, bekuno commented
retest this please

2022-02-04 22:59 UTC, fm-sys approved these changes
Should probably be fine...

2022-02-04 23:56 UTC, merged