Update bug_report.yml with current version number
cgeo/cgeo pull request #13831
Opened 2023-01-07 11:56 UTC by bekuno

Set the current c:geo version number as templete.

Maybe this should be integrated as a step in the release workflow.

2023-01-08 22:01 UTC, bekuno commented
retest this please

2023-01-09 20:41 UTC, bekuno commented
retest this please

2023-01-09 21:11 UTC, bekuno commented
retest this please

2023-01-09 21:36 UTC, SammysHP commented
I would go the other way: Replace it with a YYYY.MM.DD placeholder. Having it always up-to-date gives us false information if the reporter hasn't answered the question.

2023-02-02 22:18 UTC, bekuno commented
@Lineflyer What do you think?

2023-02-02 22:37 UTC, Lineflyer requested changes
Sorry, did not notice this PR.
I agree to @SammysHP to use a generic placeholder to avoid misinterpretation and at the same time avoid the necessity to regularly update the template.

2023-02-03 22:14 UTC, Lineflyer approved these changes

2023-02-03 22:14 UTC, merged