fix TB logging, remove legacy code, only fetch TB log page if required
cgeo/cgeo pull request #15658
Opened 2024-04-22 15:59 UTC by ztNFny

fix retrieving the CSRF token for some TB logs

make getting the TB html page conditional as it's only required for RETRIEVE logs

all log pages seem stable in their use of the new CSRF call now, so removing the legacy code, fixing https://github.com/cgeo/cgeo/issues/15648

2024-04-22 20:05 UTC, bekuno commented on main/src/androidTest/java/cgeo/geocaching/connector/gc/GCLogAPITest.java
> +    private static final String TEST_GEOCODE = "GC7E3PE"; // Am Hart
There is no cache GC7E3P.

2024-04-22 20:08 UTC, bekuno requested changes

2024-04-22 20:37 UTC, ztNFny commented
retest this please

2024-04-23 19:38 UTC, bekuno commented
retest this please

2024-04-23 19:59 UTC, bekuno approved these changes
Let's check it with the nightly watchdog.

2024-04-23 19:59 UTC, merged