finetune map button layout
cgeo/cgeo pull request #16225
Opened 2024-10-16 18:09 UTC by ztNFny

fixes https://github.com/cgeo/cgeo/issues/16212

2024-10-16 18:13 UTC, ztNFny commented
retest this please

2024-10-18 18:46 UTC, moving-bits commented on main/src/main/res/layout/map_zoom_control.xml
> +            android:tooltipText="@string/quick_settings"
tooltipText and contentDescription should point to "follow my position", currently a long-tap on this icon would show a "quick settings" tooltip

2024-10-18 18:50 UTC, moving-bits commented on main/src/main/res/values/styles.xml
> +        <!--<item name="android:tint">@color/osm_zoomcontrol</item>-->
can be removed (as well as in style above)

2024-10-18 18:51 UTC, moving-bits requested changes
Thanks for diving into this, looks much cleaner now!
Have only two small nitpicks, see comments. Thanks!

2024-10-18 21:32 UTC, moving-bits commented
One additional question:

Without this PR, the map overlay buttons (zoom controls, quick settings, follow my location etc.) have different levels of transparency/opaqueness:

![image](https://github.com/user-attachments/assets/99385624-943f-4193-ad0b-8902e1743daf)

As you can see in the screenshot, zoom buttons are a bit more opaque than map quick settings and route/track quick settings.

With this PR, all buttons will have the higher transparency of those buttons (= less opaqueness), which makes it harder to read the button depending on what beneath them (like the motorway in those screenshots):

![image](https://github.com/user-attachments/assets/3de69046-7d42-43e1-ad02-995f2e11fb9f)

Can you adjust all map overlay buttons to have the same transparency, based on the more opaque version of the zoom controls in the first screenshot? Thanks.

2024-10-18 21:43 UTC, ztNFny commented
The different opaqueness levels were a bug 😉

2024-10-19 07:01 UTC, moving-bits commented
> The different opaqueness levels were a bug 😉 Zoom buttons had 2 half-transparent layers on top of each other

Yeah, I know, and it's good that it will be fixed by this PR. Still, the resulting opaqueness of this double-layering was better than the slight opaqueness of the other buttons. So how can we increase the opaqueness without double-layering of images?

2024-10-19 07:20 UTC, SammysHP commented
I prefer this version. The buttons can be seen sufficiently and I am still able to guess what's behind them.

2024-10-19 10:30 UTC, ztNFny commented
I've adjusted opacity to be between the 2 old ones, don't think anyone would notice the change unless in a direct comparison

2024-10-19 10:31 UTC, ztNFny reviewed
I've adjusted opacity to be between the 2 old ones, don't think anyone would notice the change unless in a direct comparison

2024-10-19 11:15 UTC, merged