don't enable live map if filter context is explicitly set
cgeo/cgeo pull request #16339
Opened 2024-11-10 16:11 UTC by ztNFny

if map filter context is explicitly set to GeocacheFilterContext.FilterType.TRANSIENT don't enable Live mode, no matter what map type is displayed

@moving-bits there's a lot of "magic" happening in determining when to show which caches (only selected, stored, live) that's quite intransparent even after debugging this code. Thus I'm asking for your review as most of this seems to come from you.
Maybe this magic could also be replaced by a more transparent implementation, but I fear that'd be a big rewrite. Or maybe it's not so magic after all and I'm just missing something??

fixes https://github.com/cgeo/cgeo/issues/16338

2024-11-10 16:50 UTC, ztNFny commented
marking as don't merge as this is probably not a good approach based on comments - hoping for a better implementation :-)

2024-11-15 22:55 UTC, ztNFny commented
let's try this in another way. As UMTT_Viewport is not used outside of WIG it shouldn't have any additional impact

2024-11-16 18:16 UTC, moving-bits requested changes
> let's try this in another way. As UMTT_Viewport is not used outside of WIG it shouldn't have any additional impact

This seems to work, technically, for displaying the zone without any other cache, similar to navigating to a single cache, but still gives an inconsistent UX:
- on mapping a single cache with "navigate to", the map's title changes to the name of this cache,
- whereas on "show this zone on map", the map title stays at "offline", though not displaying any offline caches.

Thus, if pursuing this way, we should use the zone name as title (see `UnifiedMapActivity.calculateTitle()`), and we should rename the `UnifiedMapTypeType` from `UMTT_Viewport` to something WIG-related.

2024-11-17 17:30 UTC, ztNFny commented
> Thus, if pursuing this way, we should use the zone name as title (see `UnifiedMapActivity.calculateTitle()`), and we should rename the `UnifiedMapTypeType` from `UMTT_Viewport` to something WIG-related.

While that Feature Request is unrelated to this PR I nevertheless added it to get this PR passed.

2024-11-17 17:42 UTC, eddiemuc approved these changes
LGTM. I have two minor comments only

2024-11-17 17:42 UTC, eddiemuc commented on main/src/main/java/cgeo/geocaching/maps/DefaultMap.java
> +            Log.e("Launching UnifiedMap in viewport mode, viewport=" + viewport + ")");
Use `Log.iForce()` for info logs which should appear in the logfile anyway.

2024-11-17 17:42 UTC, eddiemuc commented on main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java
> +    public UnifiedMapType(final Viewport viewport, final String title) {
With this new constructor in place, I assume that the constructor taking only a Viewport (not a name) is no longer used. Thus it should be removed.

2024-11-17 17:51 UTC, eddiemuc commented on main/src/main/java/cgeo/geocaching/unifiedmap/UnifiedMapType.java
> +    public UnifiedMapType(final Viewport viewport, final String title) {
I introduced it for Wherigos... it was not there before. But as said, it is minor. No harm in leaving it in

2024-11-17 17:51 UTC, merged