fix #9193: hard-code point instead of language-specific separator
cgeo/cgeo pull request #9196
Opened 2020-10-16 16:09 UTC by eddiemuc

fix #9193: hard-code point instead of language-specific separator

2020-10-16 17:06 UTC, UniQP commented
@eddiemuc Have you seen https://github.com/cgeo/cgeo/issues/9193#issuecomment-710162730 ?

2020-10-16 17:24 UTC, eddiemuc commented
> @eddiemuc Have you seen [#9193 (comment)](https://github.com/cgeo/cgeo/issues/9193#issuecomment-710162730) ?

I don't understand this comment. Can you elaborate?

2020-10-18 10:22 UTC, UniQP requested changes
If we used the unlocalized version for DECMINUTE, we should also use it for other formats (DECSECOND, …).

2020-10-18 10:22 UTC, UniQP commented on main/src/cgeo/geocaching/location/GeopointFormatter.java
>                  return String.format(Locale.getDefault(), "%c%d %02d%c%03d %c%d %02d%c%03d",
```suggestion
                return String.format((Locale) null, "%c%d %02d.%03d %c%d %02d.%03d",
```
and remove the `'.'` arguments.

2020-10-18 10:22 UTC, UniQP commented on main/src/cgeo/geocaching/location/GeopointFormatter.java
>              case LAT_LON_DECMINUTE_SHORT:
The example in the enum comment also needs to be adapted and should mention that the string in unlocalized.

2020-10-18 11:00 UTC, eddiemuc commented
> If we used the unlocalized version for DECMINUTE, we should also use it for other formats (DECSECOND, …).

Have you checked whether this has no unwanted side effects on other parts of c:geo?

2020-10-18 11:20 UTC, eddiemuc commented
HI @UniQP thanks for the review. You made good points, I decided to approach this a different way based on your feedback.

I now introduced a NEW enum value `LAT_LON_DECMINUTE_SHORT_POINTHARDCODED` and changed the relevant placed to use this one instead of the other value `LAT_LON_DECMINUTE_SHORT` when exporting waypoints to persnoal note. That way we can be sure I don't break existing functionality where maybe the language-specific settings are wanted and needed.

I squashed commits and force-pushed the change, maybe you (or someone) could take a second look?

2020-10-18 12:14 UTC, UniQP commented on main/src/cgeo/geocaching/location/GeopointFormatter.java
>                  return String.format(Locale.getDefault(), "%c%d %02d%c%03d %c%d %02d%c%03d",
@eddiemuc Also applies to new version

2020-10-18 12:20 UTC, UniQP requested changes

2020-10-18 12:20 UTC, UniQP commented on main/src/cgeo/geocaching/location/GeopointFormatter.java
> +        /** Example: "N10 12.345 W5 12.345" (always use point, independent from language settings) */
```suggestion
        /** Example: "N10 12.345 W5 12.345" (unlocalized) */
```

2020-10-18 12:20 UTC, UniQP commented on main/src/cgeo/geocaching/location/GeopointFormatter.java
> +        LAT_LON_DECMINUTE_SHORT_POINTHARDCODED,
```suggestion
        LAT_LON_DECMINUTE_SHORT_RAW,
```

2020-10-18 12:55 UTC, eddiemuc commented on main/src/cgeo/geocaching/location/GeopointFormatter.java
> +        /** Example: "N10 12.345 W5 12.345" (always use point, independent from language settings) */
done

2020-10-18 12:57 UTC, eddiemuc commented on main/src/cgeo/geocaching/location/GeopointFormatter.java
> +        LAT_LON_DECMINUTE_SHORT_POINTHARDCODED,
done

2020-10-18 13:26 UTC, eddiemuc commented on main/src/cgeo/geocaching/location/GeopointFormatter.java
>                  return String.format(Locale.getDefault(), "%c%d %02d%c%03d %c%d %02d%c%03d",
done

2020-10-18 14:02 UTC, eddiemuc commented
@UniQP I believe I fixed all your comments according to your suggestions (I am a little overwhelmed by GitHub GUI, so I really hope I don't miss anything). If there's anything left, please drop a short hint.

2020-10-19 10:51 UTC, UniQP approved these changes

2020-10-19 10:51 UTC, merged